/*******Bismillahir-Rahmanir-Rahim**********/
/*
Name         : Abu Rifat Muhammed Al Hasib
Institution  : University of Barisal, Bangladesh
Github       : abu-rifat
Codeforces   : AbuRifatMuhammed
AtCoder      : AbuRifatMuhammed
codechef     : aburifat
SPOJ         : abu_rifat
Toph         : aburifat
UvaOJ        : aburifat
DevSkill     : abu_rifat
lightoj      : Abu Rifat Muhammed Al Hasib
facebook     : https://www.facebook.com/a.r.m.al.hasib/
linkedin     : https://www.linkedin.com/in/abu-rifat-534258142/
Email        : rifat.cse4.bu@gmail.com, armalhasib@gmail.com
*/

/*
Online Judge    : Project Euler
Problem No      : 44
Problem Name    : 
Solving Method  : 

*/

/*
Problem Statement : 
Problem 44
==========
   Pentagonal numbers are generated by the formula, P[n]=n(3n−1)/2. The first
   ten pentagonal numbers are:
                  1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
   It can be seen that P[4] + P[7] = 22 + 70 = 92 = P[8]. However, their
   difference, 70 − 22 = 48, is not pentagonal.
   Find the pair of pentagonal numbers, P[j] and P[k], for which their sum
   and difference are pentagonal and D = |P[k] − P[j]| is minimised; what is
   the value of D?
*/


#include<bits/stdc++.h>
using namespace std;
typedef long long ll;

int main()
{

    return 0;
}
/***********Alhamdulillah***********/
