/*******Bismillahir-Rahmanir-Rahim**********/
/*
Name         : Abu Rifat Muhammed Al Hasib
Institution  : University of Barisal, Bangladesh
Github       : abu-rifat
Codeforces   : AbuRifatMuhammed
AtCoder      : AbuRifatMuhammed
codechef     : aburifat
SPOJ         : abu_rifat
Toph         : aburifat
UvaOJ        : aburifat
DevSkill     : abu_rifat
lightoj      : Abu Rifat Muhammed Al Hasib
facebook     : https://www.facebook.com/a.r.m.al.hasib/
linkedin     : https://www.linkedin.com/in/abu-rifat-534258142/
Email        : rifat.cse4.bu@gmail.com, armalhasib@gmail.com
*/

/*
Online Judge    : Project Euler
Problem No      : 297
Problem Name    : 
Solving Method  : 

*/

/*
Problem Statement : 
Problem 297
===========
   Each new term in the Fibonacci sequence is generated by adding the
   previous two terms.
   Starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21,
   34, 55, 89.
   Every positive integer can be uniquely written as a sum of nonconsecutive
   terms of the Fibonacci sequence. For example, 100 = 3 + 8 + 89.
   Such a sum is called the Zeckendorf representation of the number.
   For any integer n>0, let z(n) be the number of terms in the Zeckendorf
   representation of n.
   Thus, z(5) = 1, z(14) = 2, z(100) = 3 etc.
   Also, for 0<n<10^6, ∑ z(n) = 7894453.
   Find ∑ z(n) for 0<n<10^17.
*/


#include<bits/stdc++.h>
using namespace std;
typedef long long ll;

int main()
{

    return 0;
}
/***********Alhamdulillah***********/
