/*******Bismillahir-Rahmanir-Rahim**********/
/*
Name         : Abu Rifat Muhammed Al Hasib
Institution  : University of Barisal, Bangladesh
Github       : abu-rifat
Codeforces   : AbuRifatMuhammed
AtCoder      : AbuRifatMuhammed
codechef     : aburifat
SPOJ         : abu_rifat
Toph         : aburifat
UvaOJ        : aburifat
DevSkill     : abu_rifat
lightoj      : Abu Rifat Muhammed Al Hasib
facebook     : https://www.facebook.com/a.r.m.al.hasib/
linkedin     : https://www.linkedin.com/in/abu-rifat-534258142/
Email        : rifat.cse4.bu@gmail.com, armalhasib@gmail.com
*/

/*
Online Judge    : Project Euler
Problem No      : 45
Problem Name    : 
Solving Method  : 

*/

/*
Problem Statement : 
Problem 45
==========
   Triangle, pentagonal, and hexagonal numbers are generated by the following
   formulae:
   Triangle     T[n]=n(n+1)/2    1, 3, 6, 10, 15, ...
   Pentagonal   P[n]=n(3n−1)/2   1, 5, 12, 22, 35, ...
   Hexagonal    H[n]=n(2n−1)     1, 6, 15, 28, 45, ...
   It can be verified that T[285] = P[165] = H[143] = 40755.
   Find the next triangle number that is also pentagonal and hexagonal.
*/


#include<bits/stdc++.h>
using namespace std;
typedef long long ll;

int main()
{

    return 0;
}
/***********Alhamdulillah***********/
