/*******Bismillahir-Rahmanir-Rahim**********/
/*
Name         : Abu Rifat Muhammed Al Hasib
Institution  : University of Barisal, Bangladesh
Github       : abu-rifat
Codeforces   : AbuRifatMuhammed
AtCoder      : AbuRifatMuhammed
codechef     : aburifat
SPOJ         : abu_rifat
Toph         : aburifat
UvaOJ        : aburifat
DevSkill     : abu_rifat
lightoj      : Abu Rifat Muhammed Al Hasib
facebook     : https://www.facebook.com/a.r.m.al.hasib/
linkedin     : https://www.linkedin.com/in/abu-rifat-534258142/
Email        : rifat.cse4.bu@gmail.com, armalhasib@gmail.com
*/

/*
Online Judge    : Project Euler
Problem No      : 288
Problem Name    : 
Solving Method  : 

*/

/*
Problem Statement : 
Problem 288
===========
   For any prime p the number N(p,q) is defined byN(p,q) = ∑[n=0 to q]
   T[n]*p^n
   with T[n] generated by the following random number generator:
   S[0] = 290797
   S[n+1] = S[n]^2 mod 50515093
   T[n] = S[n] mod p
   Let Nfac(p,q) be the factorial of N(p,q).
   Let NF(p,q) be the number of factors p in Nfac(p,q).
   You are given that NF(3,10000) mod 3^20=624955285.
   Find NF(61,10^7) mod 61^10
*/


#include<bits/stdc++.h>
using namespace std;
typedef long long ll;

int main()
{

    return 0;
}
/***********Alhamdulillah***********/
