/*******Bismillahir-Rahmanir-Rahim**********/
/*
Name         : Abu Rifat Muhammed Al Hasib
Institution  : University of Barisal, Bangladesh
Github       : abu-rifat
Codeforces   : AbuRifatMuhammed
AtCoder      : AbuRifatMuhammed
codechef     : aburifat
SPOJ         : abu_rifat
Toph         : aburifat
UvaOJ        : aburifat
DevSkill     : abu_rifat
lightoj      : Abu Rifat Muhammed Al Hasib
facebook     : https://www.facebook.com/a.r.m.al.hasib/
linkedin     : https://www.linkedin.com/in/abu-rifat-534258142/
Email        : rifat.cse4.bu@gmail.com, armalhasib@gmail.com
*/

/*
Online Judge    : Project Euler
Problem No      : 395
Problem Name    : 
Solving Method  : 

*/

/*
Problem Statement : 
Problem 395
===========
   The Pythagorean tree is a fractal generated by the following procedure:
   Start with a unit square. Then, calling one of the sides its base (in the
   animation, the bottom side is the base):
    1. Attach a right triangle to the side opposite the base, with the
       hypotenuse coinciding with that side and with the sides in a 3-4-5
       ratio. Note that the smaller side of the triangle must be on the
       'right' side with respect to the base (see animation).
    2. Attach a square to each leg of the right triangle, with one of its
       sides coinciding with that leg.
    3. Repeat this procedure for both squares, considering as their bases the
       sides touching the triangle.
   The resulting figure, after an infinite number of iterations, is the
   Pythagorean tree.
   It can be shown that there exists at least one rectangle, whose sides are
   parallel to the largest square of the Pythagorean tree, which encloses the
   Pythagorean tree completely.
   Find the smallest area possible for such a bounding rectangle, and give
   your answer rounded to 10 decimal places.
   p_395_pythagorean.gif
*/


#include<bits/stdc++.h>
using namespace std;
typedef long long ll;

int main()
{

    return 0;
}
/***********Alhamdulillah***********/
